version: '2'
  
services:
    
    
    IdPMS:
        image: endimion13/seal-eidas-idp
        environment:
            - EIDAS_PROPERTIES=CurrentFamilyName,CurrentGivenName,DateOfBirth,PersonIdentifier
            - SP_COUNTRY=GR
            - SP_LOGO=img/logo.png
            - SP_CONFIG_REPOSITORY=/configEidas/
            - SP_SECRET=secret
            - AUTH_DURATION=1800
            - SESSION_MANAGER_URL=https://esmo-gateway.eu
            - KEY_PASS=selfsignedpass
            - JWT_CERT_ALIAS=selfsigned
            - ASYNC_SIGNATURE=true
            - HTTPSIG_CERT_ALIAS=1
            - KEYSTORE_PATH=/home/nikos/NetBeansProjects/seal.eidas.idp/src/test/resources/testKeys/keystore.jks
            - STORE_PASS=keystorepass
            - SEAL_SUPPORTED_SIG_ALGORITHMS=RSA
            - SEAL_SUPPORTED_ENC_ALGORITHMS=RSA
            - RESPONSE_SENDER_ID=eIDAS-IdP
            - RESPONSE_RECEIVER=API_GW
            - SEAL_EXPOSE_URL=/as/authenticate
            - SEAL_ENTITY_ID=https://seal.eu/eidas-idp
            - SEAL_DEFAULT_NAME=SEAL_EIDAS_IDP
        ports:
          - 8091:8080
          - 8443:8443
        

 

